version: '3'
services:
  tasks-dev:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: bash
